name: Build webapp

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Upload production-ready files
        uses: actions/upload-artifact@v4
        with:
          name: webapp
          path: dist/
